version: '2'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  dnsmasq:
    image: andyshinn/dnsmasq
    restart: always
    ports:
     - "53535:53/tcp"
     - "53535:53/udp"
    cap_add:
     - NET_ADMIN
    command: "--address=/dev/127.0.0.1"
